# Generated by Django 5.0.1 on 2024-02-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='Exteriors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InteriorName', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='interiors/')),
                ('second_image', models.ImageField(default='Your default value here', upload_to='interiors/')),
                ('third_image', models.ImageField(default='Your default value here', upload_to='interiors/')),
                ('short_description', models.CharField(default='Your default value here', max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('completion_year', models.PositiveIntegerField(verbose_name=50)),
                ('timline', models.CharField(max_length=15)),
                ('about', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interiors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InteriorName', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='interiors/')),
                ('second_image', models.ImageField(default='Your default value here', upload_to='interiors/')),
                ('third_image', models.ImageField(default='Your default value here', upload_to='interiors/')),
                ('short_description', models.CharField(default='Your default value here', max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('completion_year', models.PositiveIntegerField(verbose_name=50)),
                ('timline', models.CharField(max_length=15)),
                ('about', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('category', models.CharField(choices=[('Scandinavian Style', 'Скандинавский стиль'), ('Modern', 'Модерн'), ('Old Modern', 'Старый модерн'), ('Baroque', 'Барокко')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
        ),
    ]
