# Generated by Django 5.0.1 on 2024-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogs',
            name='small_description',
            field=models.CharField(default='Your default value here', max_length=100),
        ),
        migrations.AlterField(
            model_name='myblogs',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
